name: Auto merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: gh pr create -B store-1 --title "Update store branch\:\\ Store 1" --body "Updating"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}